builds:
  - main: fx.go
    binary: fx
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
# archive:
#   format: tar.gz
#   replacements:
#     amd64: 64-bit
#     darwin: macOS
#     linux: Tux
#   files:
#     - README.md
#
