---
env:
  - GO111MODULE=on
builds:
  - main: fx.go
    binary: fx
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archives:
  -
    format: tar.gz
    replacements:
      amd64: 64-bit
      darwin: macOS
      linux: Tux
    files:
      - README.md
brews:
  - homepage: "https://github.com/metrue/fx"
    description: "fx, a simple but powerful Function as a Service build tools"
    folder: Formula
    commit_author:
      name: metrue
      email: h.minghe@gmail.com
    tap:
      owner: metrue
      name: homebrew-fx
    dependencies:
      - docker
