version: 2
dependencies:
    override:
        - sudo add-apt-repository ppa:masterminds/glide -y
        - sudo apt-get update
        - sudo apt-get install glide -y
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/metrue/fx

    steps:
      - checkout

      - run:
          name: Install tools
          command: |
              go get github.com/golang/dep
              cd $GOPATH/src/github.com/golang/dep
              go install ./...

      - run:
          name: Build
          command: |
              export PATH="$HOME/bin:$PATH"
              make install-deps && make clean && make build
deployment:
    production:
    branch: master
    commands:
        - echo "Not Ready Yet"
