version: 2
machine:
    services:
        - docker
dependencies:
    override:
        - sudo add-apt-repository ppa:masterminds/glide -y
        - sudo apt-get update
        - sudo apt-get install glide -y
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/metrue/fx

    steps:
      - checkout

      - run:
          name: Install tools
          command: |
              go get github.com/golang/dep
              cd $GOPATH/src/github.com/golang/dep
              go install ./...

      - run:
          name: Build and Install
          command: |
              dep ensure
              go install ./

      - run:
          name: Test
          command: |
              fx serve > server_output.log 2>&1 &
              sleep 20
              fx up examples/functions/func.js && cat server_output.log

deployment:
    production:
    branch: master
    commands:
        - echo "Not Ready Yet"
