version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/metrue/fx

    steps:
      - checkout

      - run:
          name: Build client
          command: |
              cd client && make install-deps && make clean && make build

      - run:
          name: Build server
          command: |
              cd server && make install-deps && make clean && make build

