version: 2
dependencies:
    override:
        - sudo add-apt-repository ppa:masterminds/glide -y
        - sudo apt-get update
        - sudo apt-get install glide -y
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/metrue/fx

    steps:
      - checkout

      - run:
          name: Build client
          command: |
              cd client && make install-deps && make clean && make build

      - run:
          name: Build server
          command: |
              cd server && make install-deps && make clean && make build

